on:
  push:
    branches:
      - 'cloud-gateways'
    paths:
      - 'deck/**'
      - '.insomnia/**'
jobs:
  deploy_to_clouds:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'cloud-gateways') }}
    name: Deploying Kong Configuration
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2.2.0
      with:
        node-version: "18"
    - name: Install DecK
      run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.39.2/deck_1.39.2_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp
        cp /tmp/deck /usr/local/bin/
    - name: Install Insomnia
      run: |
        curl -sL https://github.com/Kong/insomnia/releases/download/lib%408.6.1/inso-linux-8.6.1.tar.xz -o inso.tar.xz
        sudo tar -xf inso.tar.xz -C /tmp/
        cp /tmp/inso /usr/local/bin/
    - name: Export blog spec
      run: inso -w $GITHUB_WORKSPACE export spec blog -o blog.yaml --ci
    - name: Lint blog spec
      run: inso lint spec ./blog.yaml
    - name: Generate new gateway configuration
      run: deck file openapi2kong --spec blog.yaml --output-file kong.yaml
    - name: Patch blog host with mocking server
      run: deck file patch -s kong.yaml -o kong.yaml ./deck/patch/cgw_blog_patch.yaml
    - name: Add Kong plugins
      run: |
        # Add plugins based on literal config
        deck file add-plugins -s kong.yaml -o kong.yaml --config "$KONG_OIDC_CONF" --selector "$.services[*]"
        # Add plugins based on files in folder
        deck file add-plugins -s kong.yaml -o kong.yaml ./deck/plugins/*
      env:
        KONG_OIDC_CONF: ${{ secrets.KONG_OIDC_PLUGIN }}
    - name: Backup existing configuration
      run: deck gateway dump --konnect-token $KONNECT_TOKEN --konnect-control-plane-name $CP_NAME --select-tag gitops --tls-skip-verify > kong-backup.yaml
      env:
       KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
       CP_NAME: ${{ secrets.CP_NAME }}
    - name: Apply new configuration
      run: |
        deck gateway sync --konnect-token $KONNECT_TOKEN --konnect-control-plane-name $CP_NAME --select-tag gitops --parallelism 1 --tls-skip-verify kong.yaml
        sleep 10
      env:
        KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
        CP_NAME: ${{ secrets.CP_NAME }}
    - name: Run API Tests
      id: apiTests
      run: |
        inso -w $GITHUB_WORKSPACE run test -e Development "Authentication" --ci --disableCertValidation
    - name: Back out changes on failure
      if: always() && steps.apiTests.outcome == 'failure'
      run: deck gateway sync --konnect-token $KONNECT_TOKEN --konnect-control-plane-name $CP_NAME --select-tag gitops --parallelism 1 --tls-skip-verify kong-backup.yaml
      env:
        KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
        CP_NAME: ${{ secrets.CP_NAME }}
