on:
  push:
    branches:
      - 'master'
    paths:
      - 'deck/**'
      - '.insomnia/**'
jobs:
  deploy_to_clouds:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'initial commit') }}
    name: Deploying Kong Configuration
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2.2.0
      with:
        node-version: "18"
    - name: Install DecK
      run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.27.1/deck_1.27.1_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp
        cp /tmp/deck /usr/local/bin/
    - name: Install Insomnia
      run: |
        curl -sL https://github.com/Kong/insomnia/releases/download/lib%403.16.0/inso-linux-3.16.0.tar.xz -o inso.tar.xz
        sudo tar -xf inso.tar.xz -C /tmp/
        cp /tmp/inso /usr/local/bin/
    - run: inso -w $GITHUB_WORKSPACE export spec blog -o blog.yaml --ci
      name: Export blog spec
    - name: Generate new gateway configuration
      run: deck file openapi2kong --spec blog.yaml --output-file kong.yaml
    - name: Add Kong plugins
      run: |
        deck file add-plugins -s kong.yaml -o kong.yaml --config "$KONG_OIDC_CONF" --selector "$.services[*]"
        deck file add-plugins -s kong.yaml -o kong.yaml ./deck/plugins.yaml
      env:
        KONG_OIDC_CONF: ${{ secrets.KONG_OIDC_PLUGIN }}
    - name: Backup existing configuration
      run: deck dump --konnect-token $KONNECT_TOKEN --konnect-control-plane-name $CP_NAME --select-tag gitops -o kong-backup.yaml --tls-skip-verify
      env:
       KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
       CP_NAME: ${{ secrets.CP_NAME }}
    - name: Apply new configuration
      run: deck sync --konnect-token $KONNECT_TOKEN --konnect-control-plane-name $CP_NAME --select-tag gitops -s kong.yaml --parallelism 1 --tls-skip-verify
      env:
        KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
        CP_NAME: ${{ secrets.CP_NAME }}
